import { getActivePlayers, getAllPlayers, getSchedule, getRotationIntervalDays } from './database.js';
import { addDaysIso } from './time.js';
import { today } from './config.js';

// Rotation layout, with no side effects.
//
// This lives here rather than in database.js because that module deliberately
// only persists entries it is handed, and rather than in commands/rotation.js
// because the web control panel needs the same shuffle without a Discord
// interaction to reply to. Both surfaces call through here, so a rotation
// generated in the browser and one generated by /update follow identical rules.

// Lay out one night per player, spaced by intervalDays. Writes nothing.
export function buildRotation(startDateStr, intervalDays, options = {}) {
  const { playerIds = null, shuffle = true } = options;

  let pool = getActivePlayers();
  if (Array.isArray(playerIds) && playerIds.length > 0) {
    const all = getAllPlayers();
    pool = playerIds.map(id => all.find(p => p.id === Number(id))).filter(Boolean);
  }
  if (pool.length === 0) {
    throw new Error('No active players found to generate a rotation.');
  }

  const ordered = [...pool];
  if (shuffle) {
    // Fisher-Yates
    for (let i = ordered.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [ordered[i], ordered[j]] = [ordered[j], ordered[i]];
    }
  }

  const step = Math.max(1, Number(intervalDays) || 7);
  return ordered.map((player, index) => ({
    player_id: player.id,
    playerName: player.name,
    game_date: addDaysIso(startDateStr, index * step)
  }));
}

// The rotation's real cadence, measured only from nights still ahead.
//
// database.js's getRotationIntervalDays takes the first gap between any two
// pending dates, and "pending" includes past nights nobody has resolved yet.
// One night left unanswered from a month ago reports a weekly rotation as a
// 35-day one. That is harmless where that function spaces a collision apart,
// and wrong anywhere the number is shown to a person as a default.
export function upcomingIntervalDays() {
  const todayIso = today(0);
  const dates = [...new Set(
    getSchedule()
      .filter(s => s.status === 'pending' && s.game_date >= todayIso)
      .map(s => s.game_date)
  )].sort();

  const gaps = new Map();
  for (let i = 0; i + 1 < dates.length; i++) {
    const days = Math.round(
      (Date.parse(`${dates[i + 1]}T00:00:00Z`) - Date.parse(`${dates[i]}T00:00:00Z`)) / 86400000
    );
    if (days > 0) gaps.set(days, (gaps.get(days) || 0) + 1);
  }
  if (gaps.size === 0) return getRotationIntervalDays();

  // Most common gap wins, so one hand-moved night does not set the pace.
  // Ties go to the shorter interval.
  return [...gaps.entries()].sort((a, b) => b[1] - a[1] || a[0] - b[0])[0][0];
}

// The next free slot after the last night that is still ahead.
export function suggestNextStart() {
  const todayIso = today(0);
  const interval = upcomingIntervalDays();
  const pending = getSchedule()
    .filter(s => s.status === 'pending' && s.game_date >= todayIso)
    .sort((a, b) => a.game_date.localeCompare(b.game_date));
  const last = pending[pending.length - 1];
  return {
    start_date: last ? addDaysIso(last.game_date, interval) : addDaysIso(todayIso, interval),
    interval_days: interval
  };
}
